# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('class_group', models.IntegerField(default=0)),
                ('no_of_students', models.CharField(max_length=128, verbose_name='no_of_students')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_year.AcademicYear')),
            ],
        ),
    ]
